const mongoose=require('mongoose');
const dotenv=require('dotenv');
dotenv.config();
mongoose.connect(process.env.MONGO_URI||'mongodb://localhost:27017/nexusshop');

const Product=mongoose.model('Product',new mongoose.Schema({
  name:String,description:String,price:Number,comparePrice:Number,
  category:String,subCategory:String,brand:String,
  images:[{url:String}],stock:Number,sold:{type:Number,default:0},
  rating:{type:Number,default:0},numReviews:{type:Number,default:0},
  isFeatured:{type:Boolean,default:false},isActive:{type:Boolean,default:true},
  tags:[String],specifications:[{key:String,value:String}],reviews:[],
},{timestamps:true}));

const P=[
{name:'Apple AirPods Pro 2nd Gen',description:'Active Noise Cancellation with Adaptive Transparency mode. Personalized Spatial Audio with dynamic head tracking. H2 chip for smarter noise cancellation. Up to 30 hours total listening time with case. MagSafe, Lightning and Apple Watch charger compatible.',price:189.99,comparePrice:249.99,category:'Electronics',subCategory:'Audio',brand:'Apple',stock:45,sold:892,rating:4.8,numReviews:3241,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80'}],tags:['apple','wireless','airpods','noise-cancelling'],specifications:[{key:'Chip',value:'H2'},{key:'Battery',value:'6h (30h w/ case)'},{key:'Water',value:'IPX4'},{key:'Connectivity',value:'Bluetooth 5.3'}]},

{name:'Sony WH-1000XM5',description:'Industry-leading noise canceling with two processors and 8 microphones for complete silence. 30-hour battery. Crystal clear hands-free calling. Multipoint connection — connect two devices simultaneously. Wearing detection auto-pauses music.',price:279.99,comparePrice:349.99,category:'Electronics',subCategory:'Audio',brand:'Sony',stock:32,sold:1245,rating:4.8,numReviews:4567,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80'}],tags:['sony','headphones','noise-cancelling','wireless'],specifications:[{key:'Battery',value:'30 hours'},{key:'ANC',value:'Yes - Industry leading'},{key:'Driver',value:'30mm'},{key:'Weight',value:'250g'}]},

{name:'MacBook Air M3 13"',description:'Powered by the Apple M3 chip with 8-core CPU and 10-core GPU. Strikingly thin at just 11.5mm. 13.6-inch Liquid Retina display. Up to 18 hours battery. MagSafe 3 charging. Available in Midnight, Starlight, Space Gray and Silver.',price:1099.99,comparePrice:1299.99,category:'Electronics',subCategory:'Laptops',brand:'Apple',stock:18,sold:456,rating:4.9,numReviews:2890,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1611186871525-a23fc2dbaeaf?w=600&q=80'}],tags:['apple','macbook','laptop','m3'],specifications:[{key:'Chip',value:'Apple M3'},{key:'RAM',value:'8GB unified'},{key:'Storage',value:'256GB SSD'},{key:'Display',value:'13.6" Retina'},{key:'Battery',value:'18 hours'}]},

{name:'Samsung 65" Neo QLED 4K TV',description:'Quantum Matrix Technology Pro with Neo Quantum Processor 4K. Real Depth Enhancer for stunning visuals. Dolby Atmos and Object Tracking Sound Pro. Smart TV with Netflix, Prime, Disney+ built in. AMD FreeSync Premium Pro for gaming.',price:1299.99,comparePrice:1799.99,category:'Electronics',subCategory:'TVs',brand:'Samsung',stock:12,sold:234,rating:4.7,numReviews:1123,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80'}],tags:['samsung','tv','4k','qled','smart'],specifications:[{key:'Screen',value:'65 inches'},{key:'Resolution',value:'4K Ultra HD'},{key:'HDR',value:'HDR10+'},{key:'Refresh Rate',value:'120Hz'},{key:'Audio',value:'60W Dolby Atmos'}]},

{name:'iPad Pro M4 12.9"',description:'The most powerful iPad ever with Apple M4 chip. Ultra Retina XDR OLED display with tandem OLED for extreme brightness. Thinnest Apple product ever at 5.1mm. Supports Apple Pencil Pro and Magic Keyboard.',price:1199.99,comparePrice:1399.99,category:'Electronics',subCategory:'Tablets',brand:'Apple',stock:20,sold:567,rating:4.8,numReviews:2134,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80'}],tags:['apple','ipad','tablet','m4'],specifications:[{key:'Chip',value:'Apple M4'},{key:'Display',value:'12.9" Ultra Retina XDR'},{key:'Storage',value:'256GB'},{key:'Thickness',value:'5.1mm'}]},

{name:'Samsung Galaxy S25 Ultra',description:'200MP quad-camera system with AI photography. Built-in S Pen with zero latency. 6.9" Dynamic AMOLED 2X display at 120Hz. Snapdragon 8 Elite. Galaxy AI features including Live Translate, Note Assist, and Circle to Search.',price:1299.99,comparePrice:1499.99,category:'Electronics',subCategory:'Smartphones',brand:'Samsung',stock:28,sold:789,rating:4.7,numReviews:3456,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&q=80'}],tags:['samsung','android','s-pen','camera'],specifications:[{key:'Camera',value:'200MP quad'},{key:'Display',value:"6.9\" Dynamic AMOLED"},{key:'Battery',value:'5000mAh'},{key:'Storage',value:'256GB'},{key:'Processor',value:'Snapdragon 8 Elite'}]},

{name:'PlayStation 5 Slim',description:'Experience lightning-fast loading with an ultra-high speed SSD. Haptic feedback and adaptive triggers create lifelike sensations. 3D Audio brings games to life. Play full PS5 games in 4K at up to 120fps. 1TB storage.',price:449.99,comparePrice:499.99,category:'Electronics',subCategory:'Gaming',brand:'Sony',stock:15,sold:2345,rating:4.9,numReviews:8901,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600&q=80'}],tags:['playstation','gaming','console','sony','ps5'],specifications:[{key:'Storage',value:'1TB SSD'},{key:'Resolution',value:'Up to 8K'},{key:'Frame Rate',value:'Up to 120fps'},{key:'Ray Tracing',value:'Yes'}]},

{name:'ASUS ROG Zephyrus G16',description:'AMD Ryzen 9 8945HS with NVIDIA GeForce RTX 4090. 16-inch QHD+ 240Hz Nebula display. 32GB DDR5 RAM. 1TB PCIe 4.0 SSD. Ultra-slim 18.5mm chassis. MUX Switch + AMD SmartShift Max for maximum performance.',price:2499.99,comparePrice:2999.99,category:'Electronics',subCategory:'Laptops',brand:'ASUS',stock:8,sold:123,rating:4.7,numReviews:567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=80'}],tags:['asus','gaming','laptop','rtx','rog'],specifications:[{key:'CPU',value:'Ryzen 9 8945HS'},{key:'GPU',value:'RTX 4090'},{key:'RAM',value:'32GB DDR5'},{key:'Display',value:'16" 240Hz QHD+'},{key:'Storage',value:'1TB PCIe 4.0'}]},

{name:'Logitech MX Master 3S',description:'Ultra-fast MagSpeed electromagnetic scrolling. Tracks on any surface including glass. 8K DPI sensor. Quiet clicks 90% quieter. Ergonomic design proven to reduce muscle strain. Works on up to 3 devices with Easy-Switch.',price:79.99,comparePrice:99.99,category:'Electronics',subCategory:'Peripherals',brand:'Logitech',stock:89,sold:2456,rating:4.7,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80'}],tags:['logitech','mouse','wireless','productivity'],specifications:[{key:'DPI',value:'200–8000'},{key:'Battery',value:'70 days'},{key:'Connectivity',value:'Bluetooth + USB'},{key:'Buttons',value:'7'}]},

{name:'DJI Mini 4 Pro Drone',description:'Under 249g, no registration required in most countries. 4K/60fps HDR video with 10-bit D-Log M. Omnidirectional obstacle sensing. ActiveTrack 360° intelligent tracking. Up to 34 minutes flight time. 20km video transmission.',price:759.99,comparePrice:899.99,category:'Electronics',subCategory:'Cameras',brand:'DJI',stock:14,sold:345,rating:4.8,numReviews:1234,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=600&q=80'}],tags:['dji','drone','4k','camera','aerial'],specifications:[{key:'Video',value:'4K/60fps HDR'},{key:'Weight',value:'<249g'},{key:'Flight Time',value:'34 minutes'},{key:'Range',value:'20km'}]},

{name:'JBL Charge 5 Bluetooth Speaker',description:'Powerful JBL Pro Sound with punchy bass. IP67 waterproof AND dustproof. 20 hours playtime. Built-in power bank charges your devices. PartyBoost for 100+ JBL speakers. Eco-friendly recycled materials.',price:149.99,comparePrice:179.99,category:'Electronics',subCategory:'Audio',brand:'JBL',stock:67,sold:1890,rating:4.5,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80'}],tags:['jbl','speaker','bluetooth','waterproof'],specifications:[{key:'Battery',value:'20 hours'},{key:'Waterproof',value:'IP67'},{key:'Output',value:'40W'},{key:'Weight',value:'960g'}]},

{name:'Nintendo Switch OLED',description:'7-inch OLED screen with vivid colors and crisp contrast. Enhanced audio in handheld mode. Wide adjustable stand. 64GB internal storage, expandable via microSD. Play on TV, tabletop, or handheld. Includes Joy-Con controllers.',price:349.99,comparePrice:399.99,category:'Electronics',subCategory:'Gaming',brand:'Nintendo',stock:35,sold:4567,rating:4.8,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&q=80'}],tags:['nintendo','switch','gaming','portable'],specifications:[{key:'Screen',value:'7" OLED'},{key:'Storage',value:'64GB'},{key:'Battery',value:'4.5–9 hours'},{key:'Modes',value:'3 play modes'}]},

{name:'Razer DeathAdder V3 HyperSpeed',description:'Ultra-lightweight 63g design. Razer HyperSpeed Wireless — 25% faster than competitors. Focus Pro 30K optical sensor. Up to 300 hours battery life. 5 Hyperesponse buttons. Razer Chroma RGB.',price:89.99,comparePrice:109.99,category:'Electronics',subCategory:'Gaming',brand:'Razer',stock:54,sold:1234,rating:4.6,numReviews:2345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80'}],tags:['razer','mouse','gaming','wireless'],specifications:[{key:'Weight',value:'63g'},{key:'Sensor',value:'Focus Pro 30K'},{key:'Battery',value:'300 hours'},{key:'Connection',value:'HyperSpeed 2.4GHz'}]},

// ═══ FASHION ═══
{name:'Nike Air Max 270',description:'React foam midsole provides incredibly soft, responsive ride. Tallest Air unit in heel history for all-day comfort. Lightweight mesh upper for breathability. Pull tabs for easy on and off. Available in multiple colorways.',price:129.99,comparePrice:159.99,category:'Fashion',subCategory:'Shoes',brand:'Nike',stock:78,sold:3456,rating:4.5,numReviews:8901,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'}],tags:['nike','sneakers','airmax','running'],specifications:[{key:'Upper',value:'Mesh + synthetic'},{key:'Sole',value:'Air Max heel unit'},{key:'Sizes',value:'US 6–15'},{key:'Weight',value:'309g'}]},

{name:'Adidas Ultraboost 24',description:'100% recycled content Primeknit+ upper hugs your foot for a second-skin fit. Full-length BOOST midsole for incredible energy return. Torsion System for midfoot support. Continental rubber outsole for superior grip on wet and dry surfaces.',price:179.99,comparePrice:219.99,category:'Fashion',subCategory:'Shoes',brand:'Adidas',stock:62,sold:2890,rating:4.6,numReviews:5678,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80'}],tags:['adidas','boost','running','shoes'],specifications:[{key:'Upper',value:'Primeknit+'},{key:'Midsole',value:'BOOST'},{key:'Outsole',value:'Continental rubber'},{key:'Drop',value:'10mm'}]},

{name:"Levi's 511 Slim Jeans",description:"The iconic slim fit sits below the waist and is fitted through the seat and thigh with a slim leg opening. Made with FLEX technology — a flexible, durable denim that moves with you. Available in 30+ washes and inseam lengths.",price:59.99,comparePrice:79.99,category:'Fashion',subCategory:'Jeans',brand:"Levi's",stock:145,sold:6789,rating:4.4,numReviews:15678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=600&q=80'}],tags:['levis','jeans','denim','slim'],specifications:[{key:'Fit',value:'Slim'},{key:'Material',value:'99% Cotton, 1% Elastane'},{key:'Rise',value:'Mid-rise'},{key:'Closure',value:'Zip fly + button'}]},

{name:'The North Face Nuptse Jacket',description:'The original puffer jacket. 700-fill goose down insulation keeps you warm in cold conditions. Packable into its own pocket. Water-resistant DWR finish. Relaxed fit. Iconic embroidered logo patch. Available in 15+ colors.',price:269.99,comparePrice:329.99,category:'Fashion',subCategory:'Jackets',brand:'The North Face',stock:38,sold:1234,rating:4.7,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'}],tags:['north-face','jacket','puffer','winter','down'],specifications:[{key:'Fill',value:'700-fill goose down'},{key:'Water Resistance',value:'DWR'},{key:'Packable',value:'Yes'},{key:'Pockets',value:'3'}]},

{name:'Ray-Ban Aviator Classic',description:'The original aviator sunglass since 1937. Gold metal frame with crystal green lenses. Bayonet temples. UV400 protection — blocks 100% of UVA/UVB. Comes with case and cleaning cloth. Iconic style worn by pilots and celebrities.',price:154.99,comparePrice:185.99,category:'Fashion',subCategory:'Accessories',brand:'Ray-Ban',stock:72,sold:2345,rating:4.6,numReviews:6789,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80'}],tags:['rayban','sunglasses','aviator','classic'],specifications:[{key:'Frame',value:'Gold metal'},{key:'Lens',value:'Crystal green'},{key:'UV',value:'UV400 (100% blocked)'},{key:'Style',value:'RB3025 Aviator'}]},

{name:'Hoka Clifton 9',description:'The ultimate daily trainer. Cushioned EVA foam midsole with a flat waist design for a stable, responsive ride. Engineered mesh upper for breathability. Early-stage meta-rocker for smooth transitions. Versatile enough for easy runs and long distances.',price:139.99,comparePrice:159.99,category:'Fashion',subCategory:'Shoes',brand:'Hoka',stock:56,sold:1890,rating:4.7,numReviews:4567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'}],tags:['hoka','running','shoes','cushioned'],specifications:[{key:'Stack Height',value:'34mm heel / 29mm toe'},{key:'Drop',value:'5mm'},{key:'Weight',value:'252g'},{key:'Upper',value:'Engineered mesh'}]},

{name:'Supreme Box Logo Hoodie',description:'Classic Supreme Box Logo pullover hooded sweatshirt. 70% cotton, 30% polyester French terry. Kangaroo pocket. Ribbed cuffs and hem. Made in Canada. Screen printed iconic Box Logo on chest. Limited release collectible.',price:168.00,comparePrice:220.00,category:'Fashion',subCategory:'Hoodies',brand:'Supreme',stock:12,sold:890,rating:4.5,numReviews:2345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80'}],tags:['supreme','hoodie','streetwear','limited'],specifications:[{key:'Material',value:'70% Cotton, 30% Polyester'},{key:'Fit',value:'Regular'},{key:'Origin',value:'Canada'},{key:'Print',value:'Screen printed Box Logo'}]},

// ═══ HOME ═══
{name:'Dyson V15 Detect Absolute',description:'Built-in laser reveals microscopic dust invisible to the naked eye. Piezo sensor counts and sizes particles, automatically adapting suction power. HEPA filtration captures 99.97% of particles. Up to 60 minutes run time. Comes with 10 attachments.',price:649.99,comparePrice:749.99,category:'Home',subCategory:'Cleaning',brand:'Dyson',stock:22,sold:678,rating:4.7,numReviews:2345,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'}],tags:['dyson','vacuum','cordless','hepa'],specifications:[{key:'Run Time',value:'60 minutes'},{key:'Suction',value:'230 AW'},{key:'Filtration',value:'HEPA'},{key:'Bin Volume',value:'0.77L'},{key:'Weight',value:'3.1kg'}]},

{name:'Instant Pot Pro 8-in-1',description:'Pressure cook, slow cook, rice/grain cooker, steamer, sauté/sear, sous vide, yogurt maker, and warmer. 28 one-touch Smart Programs. Automatic keep-warm. Steam release switch. Cool touch handles. Up to 70% faster than traditional cooking.',price:89.99,comparePrice:119.99,category:'Home',subCategory:'Kitchen',brand:'Instant Pot',stock:67,sold:5678,rating:4.6,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80'}],tags:['instant-pot','kitchen','pressure-cooker','multi-cooker'],specifications:[{key:'Functions',value:'8-in-1'},{key:'Capacity',value:'6 Quart'},{key:'Programs',value:'28 Smart Programs'},{key:'Faster',value:'Up to 70%'}]},

{name:'Philips Hue White & Color Starter Kit',description:'16 million colors and shades of white light from 2000K warm to 6500K cool. Control with voice (Alexa, Google, Siri) or Hue app. Set schedules, scenes, and routines. Works with all smart home systems. Includes 3 A19 bulbs and Bridge.',price:199.99,comparePrice:249.99,category:'Home',subCategory:'Smart Home',brand:'Philips',stock:44,sold:1234,rating:4.5,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'}],tags:['philips','hue','smart-home','lights'],specifications:[{key:'Colors',value:'16 million'},{key:'White Range',value:'2000K–6500K'},{key:'Protocol',value:'Zigbee'},{key:'Voice Control',value:'Alexa, Google, Siri'}]},

{name:'Nespresso Vertuo Next',description:'Centrifusion technology for perfect espresso extraction. 5 cup sizes from Espresso (40ml) to Alto (414ml). Bluetooth and Wi-Fi connected. Auto-eject used capsule. 30-second heat up. Programmable cup volume. Over 40 blends and limited editions.',price:159.99,comparePrice:199.99,category:'Home',subCategory:'Kitchen',brand:'Nespresso',stock:48,sold:2345,rating:4.5,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80'}],tags:['nespresso','coffee','espresso','kitchen'],specifications:[{key:'Cup Sizes',value:'5 (40–414ml)'},{key:'Heat Up',value:'30 seconds'},{key:'Tank',value:'1.1L'},{key:'Connected',value:'Bluetooth + Wi-Fi'}]},

{name:'Purple Hybrid Premier 4 Mattress',description:'4" Purple Grid technology — the only mattress that is both pressure-relieving AND supportive at the same time. No heat trapping. Responsive support that adapts instantly. 365-night trial. Lifetime warranty. CertiPUR-US certified foams.',price:2199.99,comparePrice:2699.99,category:'Home',subCategory:'Bedroom',brand:'Purple',stock:8,sold:234,rating:4.6,numReviews:1234,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80'}],tags:['purple','mattress','sleep','bedroom'],specifications:[{key:'Purple Grid',value:'4 inches'},{key:'Trial',value:'365 nights'},{key:'Warranty',value:'Lifetime'},{key:'Height',value:'13 inches'}]},

{name:'iRobot Roomba j9+ Robot Vacuum',description:'Dirt Detective technology analyzes your home to clean where it is needed most. Auto-Empty Base holds 60 days of dirt. PrecisionVision Navigation identifies and avoids obstacles. Braava Jet m6 compatible for mop coordination. Works with Alexa and Google.',price:799.99,comparePrice:999.99,category:'Home',subCategory:'Cleaning',brand:'iRobot',stock:18,sold:456,rating:4.5,numReviews:2345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'}],tags:['irobot','roomba','robot','vacuum','smart'],specifications:[{key:'Navigation',value:'PrecisionVision AI'},{key:'Bin',value:'Auto-Empty 60 days'},{key:'Suction',value:'10x Power-Lifting'},{key:'Mapping',value:'Smart Map'}]},

// ═══ SPORTS ═══
{name:'Garmin Fenix 8 Sapphire Solar',description:'Premium multisport GPS watch with solar charging. AMOLED or MIP display options. Advanced training metrics with Body Battery. Topographic maps with satellite imagery. Dive computer to 40m. ECG app. Incident detection. Up to 29 days battery life.',price:899.99,comparePrice:1049.99,category:'Sports',subCategory:'Watches',brand:'Garmin',stock:18,sold:456,rating:4.8,numReviews:1234,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80'}],tags:['garmin','watch','gps','sports','multisport'],specifications:[{key:'Display',value:'AMOLED 1.4"'},{key:'Battery',value:'29 days (solar)'},{key:'GPS',value:'Multi-band'},{key:'Water',value:'Dive to 40m'}]},

{name:'Manduka PRO Yoga Mat 6mm',description:'The most durable yoga mat on the planet — backed by a lifetime guarantee. Dense 6mm PVC cushioning for joint protection. Closed-cell surface prevents bacteria and odor absorption. Dimensionally stable and will not stretch or deform. Free of harmful plasticizers.',price:128.99,comparePrice:148.99,category:'Sports',subCategory:'Yoga',brand:'Manduka',stock:95,sold:3456,rating:4.8,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80'}],tags:['manduka','yoga','mat','fitness'],specifications:[{key:'Thickness',value:'6mm'},{key:'Material',value:'Closed-cell PVC'},{key:'Size',value:'71" x 24"'},{key:'Warranty',value:'Lifetime'}]},

{name:'Hydro Flask 40oz Wide Mouth',description:'TempShield double-wall vacuum insulation keeps drinks cold 24 hours and hot 12 hours. Honeycomb-insulated Flex Cap. BPA-free and phthalate-free. Dishwasher safe. Powder coat finish resists peeling. Certified B Corp. Lifetime warranty.',price:49.99,comparePrice:59.99,category:'Sports',subCategory:'Hydration',brand:'Hydro Flask',stock:178,sold:12345,rating:4.8,numReviews:34567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80'}],tags:['hydro-flask','water-bottle','insulated','hiking'],specifications:[{key:'Capacity',value:'40oz'},{key:'Cold',value:'24 hours'},{key:'Hot',value:'12 hours'},{key:'Material',value:'18/8 Stainless Steel'}]},

{name:'TRX All-in-One Suspension Trainer',description:'Military-grade suspension training used by Navy SEALs and 10M+ people. Adjustable for all fitness levels — beginner to elite athlete. 300+ exercises. Door anchor, mesh bag and workout guide included. Works anywhere — home, gym, outdoors.',price:179.99,comparePrice:214.99,category:'Sports',subCategory:'Fitness',brand:'TRX',stock:72,sold:2345,rating:4.5,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80'}],tags:['trx','fitness','suspension','training'],specifications:[{key:'Max Load',value:'350 lbs'},{key:'Exercises',value:'300+'},{key:'Suitable For',value:'All fitness levels'},{key:'Anchors',value:'Door + outdoor'}]},

{name:'WHOOP 4.0 Fitness Tracker',description:'The most advanced fitness and health wearable ever made. Continuous 24/7 health monitoring. Strain Coach guides your daily effort. Recovery score integrates sleep, HRV, and resting HR. No screen, no distractions. Waterproof 4ATM. Any-wear band system.',price:239.99,comparePrice:279.99,category:'Sports',subCategory:'Wearables',brand:'WHOOP',stock:45,sold:1234,rating:4.4,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80'}],tags:['whoop','fitness','tracker','health'],specifications:[{key:'Battery',value:'4–5 days'},{key:'Waterproof',value:'4ATM'},{key:'Sensors',value:'PPG, SpO2, Skin temp'},{key:'Membership',value:'Required'}]},

// ═══ BOOKS ═══
{name:'Atomic Habits by James Clear',description:'The #1 New York Times bestseller with 10M+ copies sold worldwide. A revolutionary framework for improving every day through tiny changes. James Clear distills the most fundamental information about habit formation to help you build better habits.',price:16.99,comparePrice:26.99,category:'Books',subCategory:'Self Help',brand:'Random House',stock:350,sold:45678,rating:4.9,numReviews:123456,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80'}],tags:['atomic-habits','self-help','habits','bestseller'],specifications:[{key:'Author',value:'James Clear'},{key:'Pages',value:'320'},{key:'Publisher',value:'Penguin Random House'},{key:'Year',value:'2018'}]},

{name:'The Alchemist by Paulo Coelho',description:'One of the bestselling books in history, selling over 65 million copies in 80+ languages. A mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of treasure. A transformative tale about following your dreams.',price:14.99,comparePrice:18.99,category:'Books',subCategory:'Fiction',brand:'HarperCollins',stock:280,sold:23456,rating:4.7,numReviews:67890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80'}],tags:['alchemist','coelho','fiction','philosophy'],specifications:[{key:'Author',value:'Paulo Coelho'},{key:'Pages',value:'208'},{key:'Language',value:'English'},{key:'Editions',value:'25th Anniversary'}]},

{name:'Clean Code by Robert C. Martin',description:'A handbook of agile software craftsmanship. Even bad code can function, but if code isn\'t clean, it can bring a development organization to its knees. Covers naming, functions, comments, formatting, error handling and much more.',price:39.99,comparePrice:54.99,category:'Books',subCategory:'Tech',brand:'Prentice Hall',stock:220,sold:12345,rating:4.6,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80'}],tags:['coding','programming','software','clean-code'],specifications:[{key:'Author',value:'Robert C. Martin'},{key:'Pages',value:'464'},{key:'Publisher',value:'Prentice Hall'},{key:'Level',value:'Intermediate–Advanced'}]},

{name:'Deep Work by Cal Newport',description:'Rules for Focused Success in a Distracted World. Deep work is the ability to focus without distraction on a cognitively demanding task. Becoming increasingly rare and valuable. The book shows you how to cultivate this skill.',price:17.99,comparePrice:25.99,category:'Books',subCategory:'Self Help',brand:'Grand Central',stock:195,sold:9876,rating:4.7,numReviews:18765,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&q=80'}],tags:['deep-work','productivity','focus','newport'],specifications:[{key:'Author',value:'Cal Newport'},{key:'Pages',value:'304'},{key:'Publisher',value:'Grand Central'},{key:'Type',value:'Non-fiction'}]},

{name:'The Psychology of Money',description:'19 short stories exploring the strange ways people think about money. Morgan Housel focuses on the behavior side of finance and investing. Simple and obvious financial principles that are routinely violated. Used by millions of investors worldwide.',price:18.99,comparePrice:24.99,category:'Books',subCategory:'Finance',brand:'Harriman House',stock:234,sold:15678,rating:4.8,numReviews:34567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80'}],tags:['money','finance','investing','psychology'],specifications:[{key:'Author',value:'Morgan Housel'},{key:'Pages',value:'256'},{key:'Publisher',value:'Harriman House'},{key:'Year',value:'2020'}]},

// ═══ BEAUTY ═══
{name:'Dyson Airwrap Complete',description:'Styles and finishes with no extreme heat. The Coanda effect automatically wraps hair. 6 attachments for all hair types and styles — curl, wave, smooth, volumize, dry and hide frizz. Now with new attachments for finer, straighter hair.',price:549.99,comparePrice:649.99,category:'Beauty',subCategory:'Hair',brand:'Dyson',stock:18,sold:1234,rating:4.6,numReviews:4567,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80'}],tags:['dyson','hair','airwrap','styling'],specifications:[{key:'Technology',value:'Coanda effect'},{key:'Attachments',value:'6 included'},{key:'Heat',value:'No extreme heat'},{key:'Voltage',value:'110–120V'}]},

{name:'La Mer The Moisturizing Cream',description:'The legendary Crème de la Mer. Miracle Broth is the heart of all La Mer formulas — a seawater fermentation of sea kelp. Visibly heals and renews. Softens, hydrates and restores. A transformative experience from first application.',price:185.00,comparePrice:220.00,category:'Beauty',subCategory:'Skincare',brand:'La Mer',stock:35,sold:2345,rating:4.5,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80'}],tags:['la-mer','moisturizer','luxury','skincare'],specifications:[{key:'Size',value:'30ml / 1oz'},{key:'Key Ingredient',value:'Miracle Broth'},{key:'Skin Type',value:'All types'},{key:'Origin',value:'USA'}]},

{name:'Charlotte Tilbury Pillow Talk Lipstick',description:"The world's most wanted lipstick shade. A perfect pinky-nude matte color that works on all skin tones. K.I.S.S.I.N.G formula moisturizes lips while delivering full color. Lasts up to 8 hours. As worn by Kim Kardashian, Bella Hadid and more.",price:34.99,comparePrice:42.99,category:'Beauty',subCategory:'Makeup',brand:'Charlotte Tilbury',stock:112,sold:8901,rating:4.8,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1586495777744-4e6232bf2f9e?w=600&q=80'}],tags:['charlotte-tilbury','lipstick','makeup','pillow-talk'],specifications:[{key:'Finish',value:'Matte'},{key:'Shade',value:'Pillow Talk'},{key:'Size',value:'3.5g'},{key:'Lasts',value:'8 hours'}]},

{name:'Fenty Beauty Pro Filt\'r Foundation',description:"50 inclusive shades for all skin tones — from the lightest ivory to the deepest ebony. Buildable medium-to-full coverage. Long-wearing 24-hour formula. Soft-matte finish controls oil. SPF 15. Created by Rihanna. Oil-free and non-comedogenic.",price:38.99,comparePrice:45.99,category:'Beauty',subCategory:'Makeup',brand:'Fenty Beauty',stock:134,sold:12345,rating:4.7,numReviews:34567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80'}],tags:['fenty','foundation','makeup','inclusive'],specifications:[{key:'Shades',value:'50 inclusive'},{key:'Coverage',value:'Medium to Full'},{key:'Finish',value:'Soft-Matte'},{key:'SPF',value:'15'}]},

{name:'The Ordinary Hyaluronic Acid 2%',description:'Multi-molecular hyaluronic acid crosspolymer complex with five weights of HA targeting the skin surface and multiple lower epidermal layers. Ultra-pure formula with no fragrance. Vegan. Suitable for all skin types including sensitive.',price:9.99,comparePrice:14.99,category:'Beauty',subCategory:'Skincare',brand:'The Ordinary',stock:289,sold:34567,rating:4.7,numReviews:89012,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80'}],tags:['ordinary','hyaluronic','serum','affordable'],specifications:[{key:'HA Concentration',value:'2%'},{key:'HA Crosspolymer',value:'1%'},{key:'Size',value:'30ml'},{key:'Vegan',value:'Yes'}]},

// ═══ MORE ELECTRONICS ═══
{name:'Apple Watch Ultra 2',description:'The most rugged and capable Apple Watch. Precision dual-frequency GPS. Up to 60 hours battery with Low Power Mode. Action Button for instant access. Flat sapphire front crystal. Titanium case. Siren loud enough to hear from 180 meters.',price:799.99,comparePrice:899.99,category:'Electronics',subCategory:'Wearables',brand:'Apple',stock:25,sold:678,rating:4.8,numReviews:2345,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&q=80'}],tags:['apple','watch','ultra','smartwatch'],specifications:[{key:'Case',value:'49mm Titanium'},{key:'Display',value:'Always-On Retina'},{key:'Battery',value:'60 hours'},{key:'GPS',value:'L1 + L5 dual-frequency'},{key:'Water',value:'100m WR'}]},

{name:'Google Pixel 9 Pro',description:'Google AI-powered smartphone with the sharpest Pixel camera ever. Triple rear camera with 50MP main, 48MP ultrawide, and 48MP telephoto with 5x optical zoom. Tensor G4 chip. 6.3-inch LTPO OLED display. 7 years of OS updates guaranteed.',price:999.99,comparePrice:1099.99,category:'Electronics',subCategory:'Smartphones',brand:'Google',stock:33,sold:456,rating:4.7,numReviews:1890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1592950630581-03335b2b4be5?w=600&q=80'}],tags:['google','pixel','android','ai','camera'],specifications:[{key:'Chip',value:'Tensor G4'},{key:'Camera',value:'50MP + 48MP + 48MP'},{key:'Zoom',value:'5x optical'},{key:'Display',value:'6.3\" LTPO OLED'},{key:'Battery',value:'4700mAh'}]},

{name:'Bose QuietComfort Ultra Earbuds',description:'World-class noise cancellation in a truly wireless form factor. CustomTune technology tailors sound to your ear anatomy. Immersive audio with Bose Spatial Audio. 6 hours on a charge (24 total with case). Touch controls. IPX4 splash resistant.',price:299.99,comparePrice:349.99,category:'Electronics',subCategory:'Audio',brand:'Bose',stock:42,sold:1123,rating:4.7,numReviews:3210,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1606220838315-056192d5e927?w=600&q=80'}],tags:['bose','earbuds','noise-cancelling','wireless','anc'],specifications:[{key:'ANC',value:'World-class'},{key:'Battery',value:'6h (24h with case)'},{key:'Water',value:'IPX4'},{key:'Audio',value:'Bose Spatial Audio'}]},

{name:'Dell XPS 15 OLED',description:'15.6-inch 3.5K OLED touch display with 100% DCI-P3. 13th Gen Intel Core i9-13900H. NVIDIA GeForce RTX 4070. 32GB DDR5 RAM. 1TB NVMe SSD. Thin and light at just 18mm. Thunderbolt 4. Wi-Fi 6E. Backlit keyboard.',price:2299.99,comparePrice:2699.99,category:'Electronics',subCategory:'Laptops',brand:'Dell',stock:10,sold:234,rating:4.6,numReviews:890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=600&q=80'}],tags:['dell','xps','laptop','oled','premium'],specifications:[{key:'CPU',value:'Intel Core i9-13900H'},{key:'GPU',value:'RTX 4070'},{key:'Display',value:'15.6\" 3.5K OLED'},{key:'RAM',value:'32GB DDR5'},{key:'Storage',value:'1TB NVMe'}]},

{name:'LG C3 55" OLED TV',description:'Evo OLED panel for perfect blacks and infinite contrast. a9 AI Processor Gen6. Filmmaker Mode, Dolby Vision IQ. 4x HDMI 2.1 ports for 4K@120Hz gaming. G-Sync Compatible, FreeSync Premium. webOS 23 with all major streaming apps.',price:1099.99,comparePrice:1499.99,category:'Electronics',subCategory:'TVs',brand:'LG',stock:14,sold:345,rating:4.8,numReviews:2678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80'}],tags:['lg','oled','tv','4k','gaming'],specifications:[{key:'Panel',value:'OLED Evo'},{key:'Size',value:'55 inches'},{key:'HDR',value:'Dolby Vision IQ'},{key:'Gaming',value:'4x HDMI 2.1 120Hz'},{key:'Audio',value:'60W Dolby Atmos'}]},

{name:'SteelSeries Arctis Nova Pro Wireless',description:'Multi-system wireless gaming headset. Hi-Res audio certification. Active noise cancellation with ClearCast Gen 2 AI mic. Dual wireless — 2.4GHz + Bluetooth. Hot-swap battery system — infinite playtime. Works on PC, PS5, Xbox, mobile.',price:349.99,comparePrice:399.99,category:'Electronics',subCategory:'Gaming',brand:'SteelSeries',stock:28,sold:678,rating:4.6,numReviews:1567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1612444530582-fc66183b16f7?w=600&q=80'}],tags:['steelseries','headset','gaming','wireless','anc'],specifications:[{key:'Drivers',value:'40mm hi-res'},{key:'ANC',value:'Active Noise Cancellation'},{key:'Wireless',value:'2.4GHz + Bluetooth'},{key:'Battery',value:'Infinite (hot-swap)'}]},

{name:'Anker 737 Power Bank 24000mAh',description:'24,000mAh high-capacity with 140W bi-directional fast charging. Charges MacBook Pro in 1.7 hours. Smart digital display. Three charging ports simultaneously. Charge two laptops + smartphone at once. Airline carry-on approved.',price:99.99,comparePrice:139.99,category:'Electronics',subCategory:'Accessories',brand:'Anker',stock:89,sold:4567,rating:4.5,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80'}],tags:['anker','power-bank','charging','portable'],specifications:[{key:'Capacity',value:'24,000mAh'},{key:'Max Output',value:'140W'},{key:'Ports',value:'3 (USB-C x2 + USB-A)'},{key:'Display',value:'Smart digital'}]},

{name:'GoPro HERO12 Black',description:'5.3K60 video and 27MP photos. HyperSmooth 6.0 stabilization. 10-bit color. Waterproof to 33ft. Enduro battery for 38% longer battery life in cold. GPS built-in. Live streaming 1080p. Voice control. Compatible with all GoPro accessories.',price:399.99,comparePrice:449.99,category:'Electronics',subCategory:'Cameras',brand:'GoPro',stock:38,sold:1234,rating:4.6,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&q=80'}],tags:['gopro','action-cam','4k','waterproof','video'],specifications:[{key:'Video',value:'5.3K60'},{key:'Photo',value:'27MP'},{key:'Stabilization',value:'HyperSmooth 6.0'},{key:'Waterproof',value:'33ft/10m'},{key:'GPS',value:'Yes'}]},

{name:'Samsung 990 Pro 2TB NVMe SSD',description:'PCIe 4.0 NVMe SSD delivering sequential read speeds up to 7,450 MB/s. Thermal Control Algorithm prevents throttling. 1,400K IOPS random reads. Ideal for gaming, content creation and professional workloads. AES 256-bit encryption. 5-year warranty.',price:159.99,comparePrice:199.99,category:'Electronics',subCategory:'Storage',brand:'Samsung',stock:112,sold:5678,rating:4.8,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&q=80'}],tags:['samsung','ssd','nvme','storage','pcie4'],specifications:[{key:'Capacity',value:'2TB'},{key:'Read',value:'7,450 MB/s'},{key:'Write',value:'6,900 MB/s'},{key:'Interface',value:'PCIe 4.0 x4'},{key:'Warranty',value:'5 years'}]},

{name:'NVIDIA RTX 4080 Super GPU',description:'Ada Lovelace architecture. 16GB GDDR6X VRAM. 4th-gen Tensor Cores for DLSS 3 Frame Generation. 3rd-gen RT Cores for ray tracing. 320W TDP. PCIe 4.0 x16. 3x DisplayPort 1.4 + HDMI 2.1. Game at 4K ultra settings.',price:999.99,comparePrice:1199.99,category:'Electronics',subCategory:'PC Components',brand:'NVIDIA',stock:7,sold:123,rating:4.8,numReviews:890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1591405351990-4726e331f141?w=600&q=80'}],tags:['nvidia','gpu','rtx','gaming','4k'],specifications:[{key:'VRAM',value:'16GB GDDR6X'},{key:'CUDA Cores',value:'10,240'},{key:'TDP',value:'320W'},{key:'Interface',value:'PCIe 4.0 x16'}]},

// ═══ MORE FASHION ═══
{name:'New Balance 990v6 Made in USA',description:'Iconic heritage runner crafted in the USA. Premium pigskin and mesh upper. ENCAP midsole technology with a polyurethane rim encasing a foam core. Blown rubber outsole. Endorsed by sneaker culture for decades. Versatile grey colorway.',price:184.99,comparePrice:214.99,category:'Fashion',subCategory:'Shoes',brand:'New Balance',stock:45,sold:2345,rating:4.7,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'}],tags:['new-balance','made-in-usa','sneakers','heritage'],specifications:[{key:'Upper',value:'Pigskin + mesh'},{key:'Midsole',value:'ENCAP + foam'},{key:'Origin',value:'Made in USA'},{key:'Width',value:'D/2E/4E available'}]},

{name:'Patagonia Better Sweater Fleece',description:'Heavyweight anti-pill 100% polyester fleece. Classic five-pocket styling. Zippered chest pocket doubles as a stuff sack. Side-seam hand pockets. Fair Trade Certified sewing. Bluesign-approved fabric. 51% recycled polyester.',price:139.99,comparePrice:159.99,category:'Fashion',subCategory:'Jackets',brand:'Patagonia',stock:67,sold:3456,rating:4.7,numReviews:7890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'}],tags:['patagonia','fleece','sustainable','outdoor'],specifications:[{key:'Material',value:'100% Polyester fleece'},{key:'Recycled',value:'51% recycled'},{key:'Fit',value:'Regular'},{key:'Certification',value:'Fair Trade'}]},

{name:'Uniqlo Ultra Light Down Jacket',description:'Incredibly light yet warm 90% down 10% feather fill. Packs into its own pocket for easy storage. Wind-resistant outer material. Ribbed collar for comfort. Available in 20+ colors. Machine washable. Essential layering piece.',price:79.99,comparePrice:99.99,category:'Fashion',subCategory:'Jackets',brand:'Uniqlo',stock:134,sold:12345,rating:4.5,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&q=80'}],tags:['uniqlo','down','jacket','packable','light'],specifications:[{key:'Fill',value:'90% Down / 10% Feather'},{key:'Weight',value:'Ultra Light'},{key:'Packable',value:'Into own pocket'},{key:'Care',value:'Machine washable'}]},

{name:'Rolex Submariner Date',description:'The benchmark of dive watches since 1953. Oyster case in Oystersteel. Unidirectional rotatable bezel in black Cerachrom ceramic. Calibre 3235 self-winding movement. Water-resistant to 300m. The ultimate wrist accessory for professionals.',price:9999.99,comparePrice:11500.00,category:'Fashion',subCategory:'Watches',brand:'Rolex',stock:3,sold:45,rating:4.9,numReviews:234,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80'}],tags:['rolex','watch','luxury','dive','submariner'],specifications:[{key:'Movement',value:'Calibre 3235'},{key:'Case',value:'41mm Oystersteel'},{key:'Bezel',value:'Cerachrom ceramic'},{key:'Water',value:'300m / 1000ft'}]},

{name:'Canada Goose Expedition Parka',description:'The warmest Canada Goose jacket, built for the most extreme cold weather. 625 fill power white duck down. Arctic-Tech outer shell with 4-way stretch. Removable coyote fur-trimmed hood. Rated to -30°C. Heritage Expedition Fit.',price:1095.00,comparePrice:1295.00,category:'Fashion',subCategory:'Jackets',brand:'Canada Goose',stock:12,sold:234,rating:4.7,numReviews:1234,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'}],tags:['canada-goose','parka','winter','extreme-cold','down'],specifications:[{key:'Fill',value:'625 fill power white duck down'},{key:'Rating',value:'-30°C'},{key:'Shell',value:'Arctic-Tech 85/15'},{key:'Fur',value:'Removable coyote fur hood'}]},

{name:'Lululemon Align Leggings 25"',description:'Buttery soft Nulu fabric feels like a second skin. Four-way stretch moves with you. Naked sensation — you will forget you are wearing them. High-rise design for secure fit. Hidden waistband pocket. Sweat-wicking and quick-drying.',price:118.00,comparePrice:138.00,category:'Fashion',subCategory:'Activewear',brand:'Lululemon',stock:89,sold:8901,rating:4.8,numReviews:34567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80'}],tags:['lululemon','leggings','yoga','activewear','align'],specifications:[{key:'Fabric',value:'Nulu (81% Nylon, 19% Lycra)'},{key:'Rise',value:'High-rise'},{key:'Length',value:'25 inches'},{key:'Pocket',value:'Hidden waistband'}]},

{name:'Balenciaga Triple S Sneakers',description:'The original dad shoe that started a global trend. Mesh, leather and suede upper. Sculpted triple-sole construction. Chunky silhouette. Made in Italy. Signature Balenciaga embossed branding. Available in multicolor and monochromatic versions.',price:895.00,comparePrice:1050.00,category:'Fashion',subCategory:'Shoes',brand:'Balenciaga',stock:8,sold:234,rating:4.4,numReviews:567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'}],tags:['balenciaga','triple-s','luxury','dad-shoe','designer'],specifications:[{key:'Upper',value:'Mesh + leather + suede'},{key:'Sole',value:'Triple stacked'},{key:'Origin',value:'Made in Italy'},{key:'Fit',value:'Runs large — size down'}]},

{name:'Gucci GG Marmont Mini Bag',description:'Quilted chevron matelassé leather. Double G hardware closure inspired by archive hardware from the 70s. Chain strap — can be worn on shoulder or cross-body. Internal card holder and zip pocket. Made in Italy. Dustbag included.',price:1290.00,comparePrice:1450.00,category:'Fashion',subCategory:'Bags',brand:'Gucci',stock:6,sold:89,rating:4.6,numReviews:345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80'}],tags:['gucci','bag','luxury','crossbody','mini'],specifications:[{key:'Material',value:'Quilted matelassé leather'},{key:'Hardware',value:'Double G gold-tone'},{key:'Strap',value:'Chain (shoulder + crossbody)'},{key:'Origin',value:'Made in Italy'}]},

// ═══ MORE HOME ═══
{name:'Vitamix E310 Explorian Blender',description:'10 variable speed settings plus pulse function. Aircraft-grade stainless steel 3-inch blade. Thermal protection system auto-shuts if overheated. Variable speed control and pulse feature. Self-cleaning in 30-60 seconds with warm water and a drop of soap.',price:349.99,comparePrice:449.99,category:'Home',subCategory:'Kitchen',brand:'Vitamix',stock:34,sold:1890,rating:4.8,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600&q=80'}],tags:['vitamix','blender','kitchen','smoothie'],specifications:[{key:'Motor',value:'2 HP peak'},{key:'Blade',value:'Aircraft-grade stainless'},{key:'Speeds',value:'10 variable'},{key:'Self-Clean',value:'Yes'}]},

{name:'Weber Spirit II E-310 Gas Grill',description:'3-burner propane gas grill with 30,000 BTUs of cooking power. 529 sq. in. primary cooking area. Porcelain-enameled cast iron cooking grates. Stainless steel burners. iGrill 3 compatible. Grease management system. 10-year warranty.',price:549.99,comparePrice:649.99,category:'Home',subCategory:'Outdoor',brand:'Weber',stock:15,sold:678,rating:4.6,numReviews:2345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80'}],tags:['weber','grill','bbq','outdoor','gas'],specifications:[{key:'Burners',value:'3'},{key:'BTU',value:'30,000 BTU/hr'},{key:'Cooking Area',value:'529 sq. in.'},{key:'Warranty',value:'10 years'}]},

{name:'KitchenAid Artisan Stand Mixer',description:'5.5-quart stainless steel bowl. 10 speeds. 59-point planetary mixing action. Tilt-head design for easy access. Power hub fits 10+ attachments (sold separately) for pasta, ice cream, meat grinding and more. Available in 20+ colors.',price:449.99,comparePrice:549.99,category:'Home',subCategory:'Kitchen',brand:'KitchenAid',stock:28,sold:4567,rating:4.8,numReviews:23456,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80'}],tags:['kitchenaid','mixer','baking','kitchen','stand-mixer'],specifications:[{key:'Bowl',value:'5.5 Quart stainless'},{key:'Speeds',value:'10'},{key:'Motor',value:'325W'},{key:'Hub',value:'Universal power hub'}]},

{name:'Sonos Era 300 Speaker',description:'Spatial audio speaker with Dolby Atmos support. Six Class-D amplifiers. Four tweeters + two midwoofers. Trueplay tuning auto-optimizes to your room. AirPlay 2, Bluetooth, and Wi-Fi. Control via Sonos app or voice. Pairs perfectly for stereo.',price:449.99,comparePrice:499.99,category:'Home',subCategory:'Audio',brand:'Sonos',stock:22,sold:567,rating:4.6,numReviews:1890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80'}],tags:['sonos','speaker','spatial-audio','dolby-atmos','wifi'],specifications:[{key:'Amps',value:'6 Class-D'},{key:'Dolby',value:'Dolby Atmos'},{key:'Connectivity',value:'Wi-Fi + Bluetooth + AirPlay 2'},{key:'Auto-Tune',value:'Trueplay'}]},

{name:'Casper Original Foam Mattress Queen',description:'4 ergonomic zones of support — softer under shoulders, firmer under hips for spinal alignment. AirScape perforated foam layer prevents overheating. HeatDelete bands pull heat away. CertiPUR-US certified. 100-night free trial. 10-year warranty.',price:1095.00,comparePrice:1295.00,category:'Home',subCategory:'Bedroom',brand:'Casper',stock:10,sold:345,rating:4.5,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80'}],tags:['casper','mattress','foam','sleep','queen'],specifications:[{key:'Size',value:'Queen 60" x 80"'},{key:'Height',value:'12 inches'},{key:'Zones',value:'4 ergonomic zones'},{key:'Trial',value:'100 nights free'}]},

{name:'Nest Learning Thermostat 4th Gen',description:'Now with Google AI that predicts when you are home and what temperature you like. Farsight screen shows temperature from across the room. 10-year energy history. Works with 95% of heating and cooling systems. Easy DIY install in 30 minutes.',price:249.99,comparePrice:299.99,category:'Home',subCategory:'Smart Home',brand:'Google',stock:44,sold:3456,rating:4.6,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'}],tags:['nest','thermostat','smart-home','google','energy'],specifications:[{key:'Display',value:'Farsight large screen'},{key:'AI',value:'Google AI learning'},{key:'Compatibility',value:'95% of HVAC systems'},{key:'Install',value:'DIY 30 minutes'}]},

{name:'Breville Barista Express Espresso',description:'Built-in conical burr grinder with Dose-Control Grinding grinds fresh directly into the portafilter. PID temperature control for consistent extraction. Manual microfoam milk texturing. Digital temperature control (PID). 67-oz water tank.',price:699.99,comparePrice:849.99,category:'Home',subCategory:'Kitchen',brand:'Breville',stock:16,sold:1234,rating:4.7,numReviews:4567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80'}],tags:['breville','espresso','coffee','barista','machine'],specifications:[{key:'Grinder',value:'Conical burr 25 grind settings'},{key:'Pressure',value:'9 bar'},{key:'Water Tank',value:'67 oz'},{key:'Temperature',value:'PID control'}]},

{name:'IKEA KALLAX Shelf Unit 4x4',description:'16-cube storage and display unit. Can be placed horizontally or vertically. Particleboard with foil finish. Back in fiberboard. Doors, baskets, and drawers sold separately to customize. Max load per shelf: 13 kg. Versatile room divider.',price:179.99,comparePrice:219.99,category:'Home',subCategory:'Storage',brand:'IKEA',stock:32,sold:5678,rating:4.4,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80'}],tags:['ikea','kallax','shelving','storage','furniture'],specifications:[{key:'Compartments',value:'16 (4x4)'},{key:'Size',value:'77x147 cm'},{key:'Load',value:'13kg per shelf'},{key:'Material',value:'Particleboard'}]},

// ═══ MORE SPORTS ═══
{name:'Trek Domane SL 6 Road Bike',description:'IsoSpeed front and rear decoupler for supreme comfort on rough roads. Carbon frame and fork. Shimano Ultegra Di2 12-speed electronic shifting. Hydraulic disc brakes. 700x32c tires. Internal cable routing. Clearance for 38mm tires.',price:4499.99,comparePrice:5299.99,category:'Sports',subCategory:'Cycling',brand:'Trek',stock:5,sold:67,rating:4.8,numReviews:234,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=600&q=80'}],tags:['trek','bike','road','cycling','carbon'],specifications:[{key:'Frame',value:'Carbon fiber'},{key:'Drivetrain',value:'Shimano Ultegra Di2'},{key:'Brakes',value:'Hydraulic disc'},{key:'Tires',value:'700x32c'}]},

{name:'Peloton Bike+',description:'The most immersive cycling experience at home. 23.8-inch rotating HD touchscreen. Auto-Follow resistance adjusts automatically to instructor cues. Apple GymKit integration. Immersive sound with 26W speakers. Includes weights and heart-rate monitor.',price:2495.00,comparePrice:2995.00,category:'Sports',subCategory:'Fitness',brand:'Peloton',stock:8,sold:345,rating:4.5,numReviews:2345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80'}],tags:['peloton','cycling','fitness','cardio','home-gym'],specifications:[{key:'Screen',value:'23.8" HD rotating'},{key:'Resistance',value:'100 magnetic micro-adjustments'},{key:'Audio',value:'26W stereo'},{key:'Weight Capacity',value:'297 lbs'}]},

{name:'Bowflex SelectTech 552 Dumbbells',description:'Replaces 15 sets of weights from 5 to 52.5 lbs. Adjust in 2.5 lb increments up to first 25 lbs. Turn the dial to select weight. Takes 2 seconds to adjust. Space-saving storage tray included. 6 weight amounts per arm up to 52.5 lbs.',price:399.99,comparePrice:479.99,category:'Sports',subCategory:'Fitness',brand:'Bowflex',stock:22,sold:3456,rating:4.6,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80'}],tags:['bowflex','dumbbells','weights','home-gym','adjustable'],specifications:[{key:'Weight Range',value:'5-52.5 lbs'},{key:'Adjustments',value:'15 weight settings'},{key:'Increment',value:'2.5 lbs (to 25 lbs)'},{key:'Space',value:'Replaces 15 sets'}]},

{name:'Osprey Atmos AG 65 Backpack',description:'Anti-Gravity suspension system literally lifts weight off your back. Stow-on-the-Go trekking pole attachment. Integrated rain cover. Hipbelt pockets. 65-liter capacity. LightWire frame. Fits torsos 16-22". Top lid, front zippered, and hip belt pockets.',price:299.99,comparePrice:349.99,category:'Sports',subCategory:'Hiking',brand:'Osprey',stock:28,sold:1234,rating:4.8,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80'}],tags:['osprey','backpack','hiking','camping','ag'],specifications:[{key:'Volume',value:'65 liters'},{key:'Suspension',value:'Anti-Gravity'},{key:'Rain Cover',value:'Integrated'},{key:'Fit',value:'Torso 16-22"'}]},

{name:'Titleist Pro V1 Golf Balls (Dozen)',description:'The #1 ball in golf. Exceptional distance with Drop-and-Stop control. Consistent flight with soft feel. Cast urethane elastomer cover. 388 dimples. 2.72-inch diameter. Trusted by more Tour professionals than any other ball.',price:54.99,comparePrice:64.99,category:'Sports',subCategory:'Golf',brand:'Titleist',stock:245,sold:23456,rating:4.8,numReviews:45678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=600&q=80'}],tags:['titleist','golf','pro-v1','balls'],specifications:[{key:'Count',value:'12 balls'},{key:'Cover',value:'Cast urethane elastomer'},{key:'Dimples',value:'388'},{key:'Compression',value:'87'}]},

{name:'Wilson Pro Staff 97 Tennis Racket',description:'Roger Federer signature series. 97 sq. in. head. 315g strung weight. Braided Graphite + Basalt construction. 16x19 string pattern. 27-inch length. Thin 21.5mm beam. Designed for advanced players seeking precision and control.',price:229.99,comparePrice:269.99,category:'Sports',subCategory:'Tennis',brand:'Wilson',stock:18,sold:567,rating:4.7,numReviews:1234,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&q=80'}],tags:['wilson','tennis','racket','pro-staff','federer'],specifications:[{key:'Head Size',value:'97 sq. in.'},{key:'Weight',value:'315g strung'},{key:'String Pattern',value:'16x19'},{key:'Beam',value:'21.5mm'}]},

{name:'Columbia Newton Ridge Hiking Boots',description:'Waterproof seam-sealed leather and textile upper. Techlite midsole for lightweight cushioning. Omni-Grip non-marking traction rubber outsole. Removable footbed. 200g Omni-Heat insulation. Available in wide width. Perfect for day hikes and light backpacking.',price:109.99,comparePrice:139.99,category:'Sports',subCategory:'Footwear',brand:'Columbia',stock:67,sold:4567,rating:4.4,numReviews:9876,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80'}],tags:['columbia','boots','hiking','waterproof','outdoor'],specifications:[{key:'Waterproof',value:'Seam-sealed'},{key:'Insulation',value:'200g Omni-Heat'},{key:'Outsole',value:'Omni-Grip rubber'},{key:'Shank',value:'Fiberglass'}]},

// ═══ MORE BOOKS ═══
{name:'Thinking Fast and Slow by Daniel Kahneman',description:'Nobel Prize-winning psychologist Daniel Kahneman reveals the two systems that drive the way we think. System 1 is fast, intuitive. System 2 is slower, more deliberative. Understanding both is key to making better decisions. Over 5 million copies sold.',price:17.99,comparePrice:25.99,category:'Books',subCategory:'Psychology',brand:'Farrar Straus',stock:178,sold:34567,rating:4.7,numReviews:56789,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80'}],tags:['kahneman','psychology','thinking','cognition','bestseller'],specifications:[{key:'Author',value:'Daniel Kahneman'},{key:'Pages',value:'499'},{key:'Publisher',value:'Farrar, Straus and Giroux'},{key:'Awards',value:'Nobel Prize author'}]},

{name:'Zero to One by Peter Thiel',description:'Notes on Startups, or How to Build the Future. Peter Thiel argues that copying what works is a path to 0. True innovation takes you from 0 to 1. Required reading at Stanford and Y Combinator. Concise yet profound startup bible.',price:15.99,comparePrice:22.99,category:'Books',subCategory:'Business',brand:'Crown Business',stock:234,sold:23456,rating:4.7,numReviews:34567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&q=80'}],tags:['thiel','startup','business','entrepreneurship','vc'],specifications:[{key:'Author',value:'Peter Thiel + Blake Masters'},{key:'Pages',value:'224'},{key:'Publisher',value:'Crown Business'},{key:'Year',value:'2014'}]},

{name:'The Pragmatic Programmer 20th Anniversary',description:'Your Journey to Mastery. Andrew Hunt and David Thomas present tips, anecdotes and philosophy for becoming the best programmer you can be. Covers DRY principle, orthogonality, tracer bullets, refactoring and career advice. Timeless classic updated for 2020.',price:49.99,comparePrice:64.99,category:'Books',subCategory:'Tech',brand:'Addison-Wesley',stock:156,sold:15678,rating:4.8,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&q=80'}],tags:['programming','software','pragmatic','engineering'],specifications:[{key:'Authors',value:'Hunt + Thomas'},{key:'Pages',value:'352'},{key:'Edition',value:'20th Anniversary'},{key:'Level',value:'All levels'}]},

{name:'Sapiens: A Brief History of Humankind',description:'Yuval Noah Harari takes us from the Stone Age to the Silicon Age. How did Homo sapiens come to dominate the planet? Explores biology, history, economics and religion in a sweeping narrative. Over 20 million copies sold worldwide.',price:18.99,comparePrice:26.99,category:'Books',subCategory:'History',brand:'Harper',stock:267,sold:45678,rating:4.7,numReviews:78901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80'}],tags:['sapiens','harari','history','non-fiction','bestseller'],specifications:[{key:'Author',value:'Yuval Noah Harari'},{key:'Pages',value:'464'},{key:'Publisher',value:'Harper'},{key:'Format',value:'Hardcover + Paperback'}]},

{name:'Rich Dad Poor Dad',description:"Robert Kiyosaki's classic personal finance book that has sold over 40 million copies. The key to wealth is having money work for you, not working for money. Learn about assets, liabilities, the rat race and financial freedom. The #1 personal finance book of all time.",price:12.99,comparePrice:17.99,category:'Books',subCategory:'Finance',brand:'Plata',stock:312,sold:56789,rating:4.5,numReviews:89012,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80'}],tags:['kiyosaki','finance','wealth','investing','classic'],specifications:[{key:'Author',value:'Robert T. Kiyosaki'},{key:'Pages',value:'336'},{key:'Copies Sold',value:'40+ million'},{key:'Languages',value:'51'}]},

// ═══ MORE BEAUTY ═══
{name:'Tatcha The Water Cream Moisturizer',description:'Oil-free, anti-aging moisturizer with Japanese wild rose, hadasei-3 complex and actual gold. Instantly dissolves excess surface oil while delivering a burst of deep hydration. Pore-clearing plant-based enzymes. For oily to combination skin types.',price:68.00,comparePrice:82.00,category:'Beauty',subCategory:'Skincare',brand:'Tatcha',stock:56,sold:4567,rating:4.6,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80'}],tags:['tatcha','moisturizer','japanese','skincare','oil-free'],specifications:[{key:'Size',value:'50ml'},{key:'Skin Type',value:'Oily to combination'},{key:'Key Ingredients',value:'Wild rose + hadasei-3'},{key:'Finish',value:'Matte'}]},

{name:'NARS Sheer Glow Foundation',description:'Luminous, buildable foundation provides a healthy, natural radiance. Lightweight formula delivers medium buildable coverage. Long-wearing for 16 hours. 45 inclusive shades across 6 undertones. Formulated without parabens, phthalates, and sulfates.',price:52.00,comparePrice:62.00,category:'Beauty',subCategory:'Makeup',brand:'NARS',stock:89,sold:7890,rating:4.7,numReviews:15678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80'}],tags:['nars','foundation','makeup','luminous','sheer-glow'],specifications:[{key:'Coverage',value:'Medium buildable'},{key:'Finish',value:'Natural radiance'},{key:'Shades',value:'45 inclusive'},{key:'Wear Time',value:'16 hours'}]},

{name:'Olaplex No.3 Hair Perfector',description:'Reduces breakage and visibly strengthens hair. Patented single ingredient bis-aminopropyl diglycol dimaleate repairs broken disulfide bonds. Use weekly before shampooing for optimal results. Suitable for all hair types. Salon-grade in your home.',price:28.00,comparePrice:36.00,category:'Beauty',subCategory:'Hair',brand:'Olaplex',stock:134,sold:23456,rating:4.7,numReviews:45678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80'}],tags:['olaplex','hair','repair','bonds','treatment'],specifications:[{key:'Size',value:'100ml / 3.3 oz'},{key:'Key Ingredient',value:'Bis-aminopropyl dimaleate'},{key:'Use',value:'Weekly pre-shampoo'},{key:'Hair Types',value:'All types'}]},

{name:'Urban Decay All Nighter Setting Spray',description:'Award-winning makeup setting spray with temperature control technology that fights heat, humidity, and sweat to extend the life of your makeup. Oil-free formula. Vegan. Cruelty-free. 3 sizes available. Extends makeup wear time up to 16 hours.',price:34.00,comparePrice:42.00,category:'Beauty',subCategory:'Makeup',brand:'Urban Decay',stock:178,sold:19876,rating:4.6,numReviews:34567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1586495777744-4e6232bf2f9e?w=600&q=80'}],tags:['urban-decay','setting-spray','makeup','all-nighter'],specifications:[{key:'Size',value:'118ml / 4 oz'},{key:'Wear Time',value:'16 hours'},{key:'Formula',value:'Oil-free + Vegan'},{key:'Technology',value:'Temperature control'}]},

// ═══ FOOD & GROCERY ═══
{name:'Athletic Greens AG1 Daily Greens',description:'75 vitamins, minerals and whole-food sourced ingredients in one daily scoop. NSF-certified. Probiotics + prebiotics + adaptogens. Replaces multiple supplements. Used by Tim Ferriss, Andrew Huberman and top athletes. 30-day supply.',price:79.99,comparePrice:99.99,category:'Health',subCategory:'Supplements',brand:'Athletic Greens',stock:89,sold:12345,rating:4.5,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80'}],tags:['ag1','greens','supplements','health','vitamins'],specifications:[{key:'Servings',value:'30 per pouch'},{key:'Ingredients',value:'75 whole-food sourced'},{key:'Certification',value:'NSF Certified'},{key:'Probiotics',value:'7.5 billion CFU'}]},

{name:'Optimum Nutrition Gold Standard Whey',description:'24g of blended protein per serving — whey protein isolate as primary source. 5.5g BCAAs and 4g glutamine and glutamic acid. 120 calories per serving. 70+ flavors. Over 20 years the #1 selling whey protein. Instantized for easy mixing.',price:54.99,comparePrice:69.99,category:'Health',subCategory:'Supplements',brand:'Optimum Nutrition',stock:156,sold:45678,rating:4.7,numReviews:67890,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1594498653385-d5172c532c00?w=600&q=80'}],tags:['whey','protein','gym','supplement','on'],specifications:[{key:'Protein',value:'24g per serving'},{key:'Calories',value:'120 per serving'},{key:'BCAAs',value:'5.5g'},{key:'Flavors',value:'70+'}]},

{name:'Ghirardelli Premium Chocolate Assortment',description:'Indulgent squares collection featuring Dark Chocolate, Milk Chocolate, and White Chocolate varieties. Made with premium-quality cacao. Each piece filled with caramel, raspberry, mint or sea salt. Perfect gifting box. 52-piece assortment.',price:34.99,comparePrice:44.99,category:'Health',subCategory:'Food',brand:'Ghirardelli',stock:234,sold:8901,rating:4.7,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&q=80'}],tags:['ghirardelli','chocolate','gift','premium','assortment'],specifications:[{key:'Count',value:'52 pieces'},{key:'Varieties',value:'Dark, Milk, White'},{key:'Fillings',value:'Caramel, Raspberry, Mint, Sea Salt'},{key:'Weight',value:'680g'}]},

// ═══ TOYS & KIDS ═══
{name:'LEGO Technic Bugatti Chiron 42083',description:'1:8 scale replica with W16 engine with moving pistons, working 8-speed gearbox, and independent suspension. Over 3,600 pieces. Iconic Bugatti blue and black color scheme. Rear spoiler activates on deployment. For ages 16+.',price:349.99,comparePrice:399.99,category:'Toys',subCategory:'LEGO',brand:'LEGO',stock:18,sold:1234,rating:4.9,numReviews:4567,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1560840067-ddcaeb7831d2?w=600&q=80'}],tags:['lego','technic','bugatti','car','adults'],specifications:[{key:'Pieces',value:'3,599'},{key:'Scale',value:'1:8'},{key:'Engine',value:'Working W16 pistons'},{key:'Age',value:'16+'}]},

{name:'Barbie Dreamhouse 2023 Edition',description:'3-story, 8-room dollhouse with 75+ pieces of furniture and accessories. Working elevator, 3 outdoor areas, and pool with slide. Lights and sounds throughout. Compatible with all Barbie dolls. Easy tool-free assembly for ages 3+.',price:199.99,comparePrice:249.99,category:'Toys',subCategory:'Dolls',brand:'Barbie',stock:28,sold:3456,rating:4.6,numReviews:6789,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1567596296091-c5e7d8b3a820?w=600&q=80'}],tags:['barbie','dreamhouse','dollhouse','girls','play'],specifications:[{key:'Floors',value:'3 stories, 8 rooms'},{key:'Pieces',value:'75+ furniture + accessories'},{key:'Features',value:'Elevator, pool, slide'},{key:'Age',value:'3+'}]},

{name:'Hot Wheels Ultimate Garage Playset',description:'Massive 5-foot-tall, 5-story garage holds 140 Hot Wheels cars. Includes exclusive Hot Wheels vehicle. Spiral raceway, elevator, and auto-launch. Battle zone and helicopter landing pad. Largest Hot Wheels playset ever made.',price:119.99,comparePrice:149.99,category:'Toys',subCategory:'Cars',brand:'Hot Wheels',stock:22,sold:2345,rating:4.5,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&q=80'}],tags:['hot-wheels','garage','cars','playset','boys'],specifications:[{key:'Height',value:'5 feet (5 stories)'},{key:'Capacity',value:'140+ cars'},{key:'Includes',value:'1 exclusive car'},{key:'Age',value:'4+'}]},

// ═══ PET SUPPLIES ═══
{name:'KONG Classic Dog Toy Large',description:'The gold standard of dog toys for 40+ years. Natural rubber compound. Stuffable with treats, peanut butter or KONG Easy Treat. Helps with separation anxiety, boredom, and destructive behavior. Dishwasher safe. Bounces unpredictably for extra fun.',price:15.99,comparePrice:19.99,category:'Pets',subCategory:'Dog Toys',brand:'KONG',stock:234,sold:45678,rating:4.8,numReviews:89012,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80'}],tags:['kong','dog','toy','treat','chew'],specifications:[{key:'Size',value:'Large (dogs 30-65 lbs)'},{key:'Material',value:'Natural rubber'},{key:'Dishwasher',value:'Safe'},{key:'Stuffable',value:'Yes'}]},

{name:'Royal Canin Size Health Nutrition Medium Adult',description:'Tailor-made nutrition for medium dogs 11-25 lbs between 1-7 years. Highly digestible proteins with prebiotics for optimal digestive health. Adapted energy and exclusive complex of nutrients for healthy weight maintenance. 30-pound bag.',price:79.99,comparePrice:95.99,category:'Pets',subCategory:'Dog Food',brand:'Royal Canin',stock:45,sold:6789,rating:4.6,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80'}],tags:['royal-canin','dog-food','medium','nutrition'],specifications:[{key:'Weight',value:'30 lbs bag'},{key:'Breed Size',value:'Medium (11-25 lbs)'},{key:'Life Stage',value:'Adult 1-7 years'},{key:'Protein',value:'26% min'}]},

// ═══ TOOLS & HARDWARE ═══
{name:'DeWalt 20V MAX Impact Driver Kit',description:'3-speed selector matches speed to application. 1,825 in-lbs of max torque. LED lights to illuminate work surface. Compact and lightweight design. Brushless motor for longer runtime. Includes 2 batteries, charger and kit bag.',price:179.99,comparePrice:229.99,category:'Tools',subCategory:'Power Tools',brand:'DeWalt',stock:38,sold:4567,rating:4.7,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&q=80'}],tags:['dewalt','impact-driver','drill','power-tool','20v'],specifications:[{key:'Torque',value:'1,825 in-lbs max'},{key:'Speed',value:'3-speed selector'},{key:'Battery',value:'20V MAX 2.0Ah x2'},{key:'Motor',value:'Brushless'}]},

{name:'Leatherman Wave+ Multi-Tool',description:'25 tools in one. 420HC stainless steel blades with one-hand accessible openers. Spring-action pliers and wire cutters. Screwdrivers, files, saw, scissors and can opener. Nylon sheath included. Lifetime guarantee. Made in Portland, Oregon.',price:109.99,comparePrice:129.99,category:'Tools',subCategory:'Hand Tools',brand:'Leatherman',stock:78,sold:5678,rating:4.8,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&q=80'}],tags:['leatherman','multi-tool','edc','outdoors','survival'],specifications:[{key:'Tools',value:'25 total'},{key:'Steel',value:'420HC stainless'},{key:'Origin',value:'Made in USA'},{key:'Warranty',value:'Lifetime guarantee'}]},

// ═══ OFFICE & STATIONERY ═══
{name:'Herman Miller Aeron Chair Size C',description:'The world\'s most-studied and awarded office chair. PostureFit SL supports pelvis and sacrum. 8Z Pellicle suspension distributes weight evenly. Highly adjustable for 99th percentile of body types. Tilt limiter with 3 positions. 12-year warranty.',price:1695.00,comparePrice:1895.00,category:'Office',subCategory:'Chairs',brand:'Herman Miller',stock:12,sold:345,rating:4.8,numReviews:2345,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1505798577917-a65157d3320a?w=600&q=80'}],tags:['herman-miller','aeron','ergonomic','chair','office'],specifications:[{key:'Size',value:'C (Large)'},{key:'Suspension',value:'8Z Pellicle'},{key:'Support',value:'PostureFit SL'},{key:'Warranty',value:'12 years'}]},

{name:'LG 27" 4K UHD USB-C Monitor',description:'27-inch IPS 4K UHD display with 99% sRGB. USB-C single cable connection carries power, video and data. HDR10 support. AMD FreeSync. 60Hz. Built-in display split feature. Ergonomic stand with tilt, swivel, pivot and height adjustment.',price:449.99,comparePrice:549.99,category:'Office',subCategory:'Monitors',brand:'LG',stock:24,sold:1234,rating:4.6,numReviews:3456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&q=80'}],tags:['lg','monitor','4k','usb-c','27-inch'],specifications:[{key:'Size',value:'27 inches'},{key:'Resolution',value:'3840x2160 4K'},{key:'Panel',value:'IPS'},{key:'Color',value:'99% sRGB'},{key:'Connectivity',value:'USB-C + HDMI + DP'}]},

{name:'Moleskine Classic Hardcover Notebook Large',description:'The legendary notebook used by Van Gogh, Picasso, and Hemingway. Acid-free paper. Rounded corners. Expandable inner pocket. Elastic closure band. Ribbon bookmark. 240 pages of ivory paper. Available in ruled, blank, squared and weekly planner.',price:29.99,comparePrice:37.99,category:'Office',subCategory:'Stationery',brand:'Moleskine',stock:189,sold:15678,rating:4.6,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&q=80'}],tags:['moleskine','notebook','journal','writing','stationery'],specifications:[{key:'Pages',value:'240'},{key:'Size',value:'13x21cm Large'},{key:'Cover',value:'Hard cover'},{key:'Closure',value:'Elastic band'}]},

{name:'Logitech MX Keys S Keyboard',description:'Smart illuminated wireless keyboard with perfect stroke keys. Adjusts backlight based on ambient light. Flow enables typing across 3 computers on any OS. USB-C charging. 10 days battery (5 with backlight). Easy-Switch between 3 devices.',price:109.99,comparePrice:129.99,category:'Office',subCategory:'Peripherals',brand:'Logitech',stock:56,sold:3456,rating:4.6,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80'}],tags:['logitech','keyboard','wireless','mx-keys','productivity'],specifications:[{key:'Battery',value:'10 days (backlit 5 days)'},{key:'Devices',value:'3 (Easy-Switch)'},{key:'Charging',value:'USB-C'},{key:'Backlight',value:'Smart adaptive'}]},

// ═══ TRAVEL ═══
{name:'Samsonite Omni PC Hardside Luggage 28"',description:'Micro-diamond texture polycarbonate shell. TSA-approved lock. Multi-directional spinner wheels for 360° rotation. Fully lined interior with cross straps. Side carry handles. Lightweight at 9.6 lbs. Expandable for extra packing capacity.',price:179.99,comparePrice:219.99,category:'Travel',subCategory:'Luggage',brand:'Samsonite',stock:34,sold:2345,rating:4.5,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1553531384-397c80973a0b?w=600&q=80'}],tags:['samsonite','luggage','travel','hardside','spinner'],specifications:[{key:'Size',value:'28-inch checked'},{key:'Material',value:'Polycarbonate'},{key:'Lock',value:'TSA-approved'},{key:'Wheels',value:'4-wheel spinner'},{key:'Weight',value:'9.6 lbs'}]},

{name:'Away The Carry-On Luggage',description:'Durable polycarbonate exterior. 4 smooth, 360° spinner wheels. TSA-approved combination lock. USB-C charging port (battery sold separately). Interior compression system. Lifetime warranty. Multiple colorways. Compliant with all major US airlines.',price:295.00,comparePrice:345.00,category:'Travel',subCategory:'Luggage',brand:'Away',stock:28,sold:1890,rating:4.6,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1553531384-397c80973a0b?w=600&q=80'}],tags:['away','carry-on','luggage','travel','minimal'],specifications:[{key:'Size',value:'Carry-on (fits overhead)'},{key:'Material',value:'Polycarbonate'},{key:'Lock',value:'TSA combination'},{key:'Warranty',value:'Lifetime'}]},

{name:'Kindle Paperwhite 16GB Signature Edition',description:'6.8-inch display with adjustable warm light for comfortable reading at night. 300 PPI glare-free display. Waterproof IPX8. Wireless charging. 16GB storage for thousands of books. 10-week battery life. Auto-adjusting front light.',price:149.99,comparePrice:189.99,category:'Electronics',subCategory:'Readers',brand:'Amazon',stock:67,sold:4567,rating:4.7,numReviews:23456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80'}],tags:['kindle','ebook','reader','amazon','paperwhite'],specifications:[{key:'Display',value:'6.8" 300 PPI'},{key:'Storage',value:'16GB'},{key:'Waterproof',value:'IPX8'},{key:'Battery',value:'10 weeks'},{key:'Charging',value:'Wireless + USB-C'}]},

{name:'Yeti Rambler 30oz Tumbler',description:'Double-wall vacuum insulation keeps drinks cold for 24 hours, hot for 8 hours. 18/8 stainless steel never imparts a flavor. Duracoat color stays chip-resistant. Fits most cupholders. MagSlider lid included. Dishwasher safe.',price:38.00,comparePrice:45.00,category:'Sports',subCategory:'Hydration',brand:'Yeti',stock:189,sold:23456,rating:4.7,numReviews:45678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80'}],tags:['yeti','tumbler','insulated','coffee','travel'],specifications:[{key:'Capacity',value:'30 oz'},{key:'Cold',value:'24 hours'},{key:'Hot',value:'8 hours'},{key:'Material',value:'18/8 Stainless Steel'}]},

{name:'Theragun Pro 5th Generation',description:'Professional-grade percussive therapy device with 16mm amplitude. 5 speeds (1750-2400 PPM). 6 attachments included. Bluetooth connected to Therabody app for guided routines. OLED screen. Rotating arm for hard-to-reach areas. 150-minute battery.',price:399.99,comparePrice:499.99,category:'Sports',subCategory:'Recovery',brand:'Theragun',stock:22,sold:1890,rating:4.6,numReviews:5678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1612776572997-76cc42e058c3?w=600&q=80'}],tags:['theragun','massage','recovery','percussive','muscle'],specifications:[{key:'Amplitude',value:'16mm'},{key:'Speeds',value:'5 speeds'},{key:'Attachments',value:'6 included'},{key:'Battery',value:'150 minutes'},{key:'App',value:'Bluetooth Therabody'}]},

{name:'Cuisinart 14-Cup Food Processor',description:'1-1/3 HP motor handles even the toughest jobs. Large 14-cup work bowl. Stainless steel S-blade, dough blade, and 2mm slicing/shredding discs. Spatula and instruction book included. Wide-mouth feed tube for minimal pre-cutting. Dishwasher-safe parts.',price:179.99,comparePrice:229.99,category:'Home',subCategory:'Kitchen',brand:'Cuisinart',stock:38,sold:3456,rating:4.5,numReviews:8901,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80'}],tags:['cuisinart','food-processor','kitchen','chopper'],specifications:[{key:'Capacity',value:'14 cups'},{key:'Motor',value:'1-1/3 HP'},{key:'Blades',value:'S-blade, dough blade, disc'},{key:'Parts',value:'Dishwasher safe'}]},

{name:'Crocs Classic Clog',description:'Iconic lightweight foam clogs with ventilation ports for breathability. Buoyant, water-friendly material. Easy to clean. Heel strap for active use. Jibbitz charms compatible. Slip-resistant tread. The most comfortable shoe on the planet — 300M+ sold.',price:54.99,comparePrice:64.99,category:'Fashion',subCategory:'Shoes',brand:'Crocs',stock:234,sold:56789,rating:4.5,numReviews:123456,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80'}],tags:['crocs','clogs','comfortable','casual','waterproof'],specifications:[{key:'Material',value:'Croslite foam'},{key:'Feature',value:'Ventilation ports'},{key:'Strap',value:'Pivoting heel strap'},{key:'Care',value:'Easy wipe clean'}]},

{name:'Stanley Adventure Quencher 40oz Tumbler',description:'The viral TikTok-famous tumbler. Vacuum insulation keeps drinks cold for 2 days or hot for 7 hours. Narrow base fits most cupholders. Wide ergonomic handle. Straw included. Comfort grip lid. Made with 90% recycled stainless steel.',price:45.00,comparePrice:55.00,category:'Sports',subCategory:'Hydration',brand:'Stanley',stock:312,sold:78901,rating:4.7,numReviews:89012,isFeatured:true,images:[{url:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80'}],tags:['stanley','quencher','tumbler','viral','hydration'],specifications:[{key:'Capacity',value:'40 oz'},{key:'Cold',value:'2 days with ice'},{key:'Hot',value:'7 hours'},{key:'Material',value:'90% recycled stainless'}]},

{name:'Spigen Tough Armor iPhone 15 Pro Case',description:'Military-grade MIL-STD-810G certified drop protection. Dual-layer design — hard PC back and flexible TPU bumper. Kickstand for hands-free viewing. Raised bezels protect screen and camera. Precise cutouts. Wireless charging compatible.',price:19.99,comparePrice:29.99,category:'Electronics',subCategory:'Accessories',brand:'Spigen',stock:456,sold:23456,rating:4.6,numReviews:45678,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1592950630581-03335b2b4be5?w=600&q=80'}],tags:['spigen','iphone','case','protection','kickstand'],specifications:[{key:'Certification',value:'MIL-STD-810G'},{key:'Material',value:'PC + TPU'},{key:'Kickstand',value:'Built-in'},{key:'Compatibility',value:'iPhone 15 Pro'}]},

{name:'Fujifilm Instax Mini 12 Camera',description:'Adorably stylish instant camera. New Close-Up mode for selfies and close-up shots. Auto Exposure adjusts shutter speed based on brightness. Internal mirror for easy self-portraits. Multiple colors — lilac purple, clay white, blossom pink and mint green.',price:89.99,comparePrice:109.99,category:'Electronics',subCategory:'Cameras',brand:'Fujifilm',stock:78,sold:8901,rating:4.6,numReviews:12345,isFeatured:false,images:[{url:'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&q=80'}],tags:['fujifilm','instax','instant-camera','polaroid','mini'],specifications:[{key:'Film',value:'Instax Mini (credit card size)'},{key:'Mode',value:'Close-Up + Portrait'},{key:'Exposure',value:'Auto'},{key:'Mirror',value:'Built-in selfie mirror'}]},
];

async function seed(){
  try{
    await Product.deleteMany({});
    const done=await Product.insertMany(P);
    const cats=[...new Set(done.map(p=>p.category))];
    console.log(`\n✅ Seeded ${done.length} products!\n`);
    cats.forEach(c=>{
      const n=done.filter(p=>p.category===c).length;
      console.log(`  📦 ${c}: ${n} products`);
    });
    console.log('\n🚀 http://localhost:3000\n');
  }catch(e){console.error('❌',e.message);}
  finally{mongoose.connection.close();}
}
seed();
